context("Scalar types")

test_that("Scalar type predicates work", {
  expect_true(is_scalar_list(list(1)))
  expect_false(is_scalar_list(list(1, 2)))
  expect_true(is_scalar_vector(list(1)))
  expect_true(is_scalar_numeric(1))
  expect_false(is_scalar_numeric(c(1, 2)))
  expect_true(is_integer(1:2))
  expect_false(is_scalar_integer(1:2))
  expect_true(is_scalar_integer(1L))
  expect_true(is_scalar_logical(TRUE))
  expect_false(is_scalar_logical(1))
  expect_false(is_scalar_logical(c(1, 2)))
  expect_true(is_scalar_complex(1i))
  expect_false(is_scalar_complex(c(1i, 2i)))
  expect_true(is_scalar_raw(as.raw(20)))
  expect_false(is_scalar_raw(c(as.raw(c(20, 1)))))
})