context("Type predicates")

test_that("Type predicates work", {
  expect_false(is_atomic(NULL))
  expect_true(is_vector(1:3))
  expect_true(is_vector(list(1:3)))
  expect_true(is_numeric(1))
  expect_true(is_numeric(1:3))
  expect_true(is_integer(1:3))
  expect_false(is_double(1:3))
  expect_true(is_double(c(1, 2, 3)))
  expect_true(is_atomic(as.Date("2013-01-01")))
  expect_true(is_numeric(as.Date("2013-01-01")))
  expect_true(is_numeric(as.POSIXct("2013-01-01")))
  expect_true(is_character(letters))
  expect_false(is_character(factor(letters)))
  expect_true(is_integer(factor(letters)))
  expect_true(is_logical(NA))
})